image: Visual Studio 2019

shallow_clone: true

branches:
  only:
    - main

platform: x64

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 16"
  - cmake --build . --config "Release"
  - dir /s
  - ctest .
