image: Visual Studio 2019

shallow_clone: true

branches:
  only:
    - main

platform: x64

build_script:
  - cmake -H. -Bbuild -G "Visual Studio 16" --config "Release"
  - echo 15 10 3 | .\Release\mathsolver48.exe
